<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dependance" nsURI="http://fr.sirs/dependance">
  <eClassifiers xsi:type="ecore:EClass" name="OuvrageVoirieDependance" eSuperTypes="../../sirs-core/model/sirs.ecore#//AbstractDependance">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeId" eType="#//RefOuvrageVoirieDependance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefOuvrageVoirieDependance" eSuperTypes="../../sirs-core/model/sirs.ecore#//ReferenceType">
    <eAnnotations source="couchDBDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AireStockageDependance" eSuperTypes="../../sirs-core/model/sirs.ecore#//AbstractDependance">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="materiaux" upperBound="-1"
        eType="#//MateriauDependance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MateriauDependance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="designation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeMateriauId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefMateriau"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CheminAccesDependance" eSuperTypes="../../sirs-core/model/sirs.ecore#//AbstractDependance">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeur" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="revetementId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefRevetement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutreDependance" eSuperTypes="../../sirs-core/model/sirs.ecore#//AbstractDependance">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destinationId" eType="#//RefDestinationDependance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefDestinationDependance" eSuperTypes="../../sirs-core/model/sirs.ecore#//ReferenceType">
    <eAnnotations source="couchDBDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrestationAmenagementHydraulique" eSuperTypes="../../sirs-core/model/sirs.ecore#//ObjetPhotographiable">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coutMetre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coutGlobal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="realisationInterne" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cote" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefSource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mesureDiverse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typePrestationId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefPrestation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marcheId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//Marche"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="desordreIds" upperBound="-1"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//Desordre"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ouvrageAssocieAmenagementHydrauliqueIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//OuvrageAssocieAmenagementHydraulique"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coursEauIds" upperBound="-1"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//CoursEau"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrganeProtectionCollective" eSuperTypes="../../sirs-core/model/sirs.ecore#//ObjetPhotographiable">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cote" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="observations" upperBound="-1"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//Observation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//RefTypeOrganeProtectionCollective"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefTypeOrganeProtectionCollective" eSuperTypes="../../sirs-core/model/sirs.ecore#//ReferenceType">
    <eAnnotations source="couchDBDocument"/>
  </eClassifiers>
</ecore:EPackage>
