<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aot_cot" nsURI="http://fr.sirs/aot_cot">
  <eClassifiers xsi:type="ecore:EClass" name="Convention" eSuperTypes="../../sirs-core/model/sirs.ecore#//SIRSDefaultDocument ../../sirs-core/model/sirs.ecore#//SIRSDefaultReference">
    <eAnnotations source="couchDBDocument">
      <details key="document" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date_debut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="localDate"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date_fin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="localDate"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeConventionId" eType="#//RefConvention"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentaire" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateMaj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="localDate"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organismeSignataireIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//Organisme"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contactSignataireIds" upperBound="-1"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//Contact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ouvertureBatardableIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//OuvertureBatardable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="voieAccesIds" upperBound="-1"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//VoieAcces"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="voieDigueIds" upperBound="-1"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//VoieDigue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ouvrageVoirieIds" upperBound="-1"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//OuvrageVoirie"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ouvrageFranchissementIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//OuvrageFranchissement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stationPompageIds" upperBound="-1"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//StationPompage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reseauHydrauliqueCielOuvertIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//ReseauHydrauliqueCielOuvert"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reseauHydrauliqueFermeIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//ReseauHydrauliqueFerme"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ouvrageHydrauliqueAssocieIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//OuvrageHydrauliqueAssocie"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reseauTelecomEnergieIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//ReseauTelecomEnergie"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ouvrageTelecomEnergieIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//OuvrageTelecomEnergie"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ouvrageParticulierIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//OuvrageParticulier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="echelleLimnimetriqueIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//EchelleLimnimetrique"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefConvention" eSuperTypes="../../sirs-core/model/sirs.ecore#//ReferenceType">
    <eAnnotations source="couchDBDocument">
      <details key="document" value="true"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
