<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lit" nsURI="http://fr.sirs/lit">
  <eClassifiers xsi:type="ecore:EClass" name="TronconLit" eSuperTypes="../../sirs-core/model/sirs.ecore#//TronconDigue">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="litId" eType="#//Lit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutreOuvrageLit" eSuperTypes="#//ObjetLit">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="positionId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefPosition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SeuilLit" eSuperTypes="#//ObjetLit">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="materiauId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefMateriau"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passeSportEauVive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passePoisson" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commune" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anneeConstruction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derniersTravaux" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="localDate"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derniereInspectionSurAbords"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="localDate"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derniereInspectionSurFondations"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="localDate"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derniereInspectionSurStructuresCentrales"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="localDate"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derniereInspectionSurStructuresElargies"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="localDate"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derniereInspectionSurTechniquesVegetales"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="localDate"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fondation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="complexeDrainant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coucheTransition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="techniqueVegetale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pente" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surfaceRampant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surfaceEntretien" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="riveId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefRive"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descriptionAcces" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hauteurChute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longueurTotale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longueurCoursier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeurOuvrage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ouvertureBatardableIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//OuvertureBatardable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="desordreId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//Desordre"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreBarbacanes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numCoucheComplexeDrainant"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="epaisseurComplexeDrainant"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fonctionComplexeDrainantId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefFonction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="natureComplexeDrainantId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefNature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="materiauComplexeDrainantId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefMateriau"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceComplexeDrainantId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeFondationId" eType="#//RefTypeFondationLit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hauteurFondation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coucheTransitionFondation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="palplancheFondation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numCoucheFondation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="epaisseurFondation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fonctionFondationId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefFonction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="natureFondationId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefNature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="materiauFondationId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefMateriau"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceFondationId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="techniqueVegetaleGaucheId"
        eType="#//RefTechniqueVegetaleLit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longueurStructureElargieGauche"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeurStructureElargieGauche"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numCoucheStructureElargieGauche"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="epaisseurStructureElargieGauche"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fonctionStructureElargieGaucheId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefFonction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="natureStructureElargieGaucheId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefNature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="materiauStructureElargieGaucheId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefMateriau"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceStructureElargieGaucheId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="techniqueVegetaleDroiteId"
        eType="#//RefTechniqueVegetaleLit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longueurStructureElargieDroite"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeurStructureElargieDroite"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numCoucheStructureElargieDroite"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="epaisseurStructureElargieDroite"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fonctionStructureElargieDroiteId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefFonction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="natureStructureElargieDroiteId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefNature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="materiauStructureElargieDroiteId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefMateriau"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceStructureElargieDroiteId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefSource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longueurStructureCentrale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numCoucheStructureCentrale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="epaisseurStructureCentrale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fonctionStructureCentraleId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefFonction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="natureStructureCentraleId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefNature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="materiauStructureCentraleId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefMateriau"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceStructureCentraleId"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structureStructureCentraleId"
        eType="#//RefStructureLit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numCoucheTeteAmont" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="epaisseurTeteAmont" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fonctionTeteAmontId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefFonction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="natureTeteAmontId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefNature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="materiauTeteAmontId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefMateriau"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceTeteAmontId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structureTeteAmontId" eType="#//RefStructureLit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numCoucheTeteAval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="epaisseurTeteAval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fonctionTeteAvalId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefFonction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="natureTeteAvalId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefNature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="materiauTeteAvalId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefMateriau"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceTeteAvalId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefSource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeurStructure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numCoucheAutre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="epaisseurAutre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fonctionAutreId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefFonction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="natureAutreId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefNature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="materiauAutreId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefMateriau"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAutreId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structureTeteAvalId" eType="#//RefStructureLit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="voieAccesIds" upperBound="-1"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//VoieAcces"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ouvrageFranchissementIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//OuvrageFranchissement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="voieDigueIds" upperBound="-1"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//VoieDigue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ouvrageVoirieIds" upperBound="-1"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//OuvrageVoirie"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stationPompageIds" upperBound="-1"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//StationPompage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reseauHydrauliqueFermeIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//ReseauHydrauliqueFerme"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reseauHydrauliqueCielOuvertIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//ReseauHydrauliqueCielOuvert"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ouvrageHydrauliqueAssocieIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//OuvrageHydrauliqueAssocie"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ouvrageTelecomEnergieIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//OuvrageTelecomEnergie"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reseauTelecomEnergieIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//ReseauTelecomEnergie"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ouvrageParticulierIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//OuvrageParticulier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="echelleLimnimetriqueIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//EchelleLimnimetrique"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlageDepotLit" eSuperTypes="#//ObjetLit">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hauteurMurette" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeur" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coteId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefCote"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="positionId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefPosition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="natureHautId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefNature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="natureBasId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefNature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="materiauHautId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefMateriau"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="materiauBasId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefMateriau"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ouvertureBatardableIds"
        upperBound="-1" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//OuvertureBatardable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lit">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="designation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateMaj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="localDate"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentaire" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefStructureLit">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="designation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefTypeFondationLit">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="designation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefTechniqueVegetaleLit">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="designation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjetLit" abstract="true" eSuperTypes="../../sirs-core/model/sirs.ecore#//ObjetPhotographiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="proprietes" upperBound="-1"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//ProprieteObjet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gestions" upperBound="-1"
        eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//GestionObjet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IleBancLit" eSuperTypes="#//ObjetLit">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longueur" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeur" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rattacheBerge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vegetalise" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OuvrageAssocieLit" eSuperTypes="../../sirs-core/model/sirs.ecore#//Objet">
    <eAnnotations source="couchDBDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OccupationRiveraineLit" eSuperTypes="../../sirs-core/model/sirs.ecore#//Objet">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeOccupationId" eType="#//RefOccupationLit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="riveId" eType="ecore:EClass ../../sirs-core/model/sirs.ecore#//RefRive"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefOccupationLit" eSuperTypes="../../sirs-core/model/sirs.ecore#//ReferenceType">
    <eAnnotations source="couchDBDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PenteLit" eSuperTypes="../../sirs-core/model/sirs.ecore#//Objet">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="penteMoyenne" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LargeurLit" eSuperTypes="../../sirs-core/model/sirs.ecore#//Objet">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeurMoyenne" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegimeEcoulementLit" eSuperTypes="../../sirs-core/model/sirs.ecore#//Objet">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regimeId" eType="#//RefRegimeLit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefRegimeLit" eSuperTypes="../../sirs-core/model/sirs.ecore#//ReferenceType">
    <eAnnotations source="couchDBDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomanialiteLit" eSuperTypes="../../sirs-core/model/sirs.ecore#//Objet">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZoneAtterrissementLit" eSuperTypes="../../sirs-core/model/sirs.ecore#//Objet">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regimeId" eType="#//RefZoneAtterrissementLit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefZoneAtterrissementLit" eSuperTypes="../../sirs-core/model/sirs.ecore#//ReferenceType">
    <eAnnotations source="couchDBDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DesordreLit" eSuperTypes="../../sirs-core/model/sirs.ecore#//Desordre">
    <eAnnotations source="couchDBDocument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeDesordreLitId" eType="#//RefTypeDesordreLit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefTypeDesordreLit" eSuperTypes="../../sirs-core/model/sirs.ecore#//ReferenceType">
    <eAnnotations source="couchDBDocument"/>
  </eClassifiers>
</ecore:EPackage>
